// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Bootloader

#include "ui.h"

void ui_Connectwifi_screen_init(void)
{
    ui_Connectwifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Connectwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Connectwifi);
    lv_obj_set_width(ui_Keyboard1, 309);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 55);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Connectwifi);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 25);
    lv_obj_set_x(ui_TextArea1, -80);
    lv_obj_set_y(ui_TextArea1, -103);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "SSID...");



    ui_TextArea2 = lv_textarea_create(ui_Connectwifi);
    lv_obj_set_width(ui_TextArea2, 145);
    lv_obj_set_height(ui_TextArea2, 27);
    lv_obj_set_x(ui_TextArea2, -80);
    lv_obj_set_y(ui_TextArea2, -67);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "PASSWORD...");



    ui_Button4 = lv_btn_create(ui_Connectwifi);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 86);
    lv_obj_set_y(ui_Button4, -91);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
